{% set version = "2.1.2" %}

package:
  name: w3lib
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/w3lib/w3lib-{{ version }}.tar.gz
  sha256: ed5b74e997eea2abe3c1321f916e344144ee8e9072a6f33463ee8e57f858a4b1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - w3lib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scrapy/w3lib
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Library of web-related functions
  description: |
    Python library of web-related functions such as extract base url from HTML snippets,
    translate entites on HTML strings, convert raw HTTP headers to dicts and vice-versa,
    construct HTTP auth header, converting HTML pages to unicode, etc.
  doc_url: https://w3lib.readthedocs.io
  dev_url: https://github.com/scrapy/w3lib

extra:
  recipe-maintainers:
    - nehaljwani
